// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://<>/graphql",
    "aws_appsync_region": "",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "",
};

export default awsmobile;
